### ISSUE TITLE
Mocks are not switching off

### ISSUE THREAD

**Issue by maksimsemenov** [500tech/mimic#257] opened 2018-05-31 13:54 UTC
I found this issue, which seems like a bug to me.

When I'm switching mock off, it still keeps intercepting the network request, so request becomes pending and not resolving at all. To truly disable the mock, I have to change request URL.

![ezgif-3-b15d4d001c](https://user-images.githubusercontent.com/3608139/40786248-9b32b03e-64b8-11e8-8e45-1d6ae3643d68.gif)

Please let me know if it is an expected behavior and I'm doing something wrong.

**Comment by morsdyce** [comment] 2018-06-01 12:11
That seems odd, from your gif it looks like Mimic is not mocking the request (since there is no blue M when in the request notification).

I'll try to reproduce it soon and see if it happens to me as well

**Comment by morsdyce** [comment] 2018-06-01 12:12
In general if Mimic is not mocking your request then it does nothing to it. so it's possible the issue is coming from something else.

**Comment by maksimsemenov** [comment] 2018-06-01 16:15
Yeah, it seems odd to me too. The thing is that when I'm switching mimic off (to not mocking the request), somehow request doesn't go through: it is not appearing in the network tab. But when I change the request url everything seems to work as expected (mimic is not mocking the request).

**Comment by morsdyce** [comment] 2018-06-04 20:36
I was able to reproduce the issue and was fixed with a new release v2.0.6
The problem was a refactor that did not take into account disabled mocks and did not report there are no mocks and let the request pass through. Tests will be added to prevent these in the future.

Can you please check that it is now working correctly for you now?

Thanks!

**Comment by maksimsemenov** [comment] 2018-06-04 21:12
Just checked it. it works correctly now!

Thanks a lot!

**Closed** 2018-06-04 21:12 UTC
